# Generated by Django 6.0.2 on 2026-03-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_legalpage_alter_teammember_options_legalsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpage',
            name='content',
            field=models.TextField(blank=True, help_text='Full rich text content for the page'),
        ),
        migrations.DeleteModel(
            name='LegalSection',
        ),
    ]
